template_path: base.yaml
stack_name: synapse-login-scipoolprod-base
stack_tags:
  Department: "Platform"
  Project: "Infrastructure"
  OwnerEmail: "it@sagebase.org"
dependencies:
  - prod/synapse-login-scipoolprod-sageit-cert.yaml
parameters:
  DNSDomainName: "scipoolprod.org"
  BeanstalkAppName: "synapse-login"
