template_path: app-extra.yaml
stack_name: synapse-login-scipoolprod-extra
dependencies:
  - prod/synapse-login-scipoolprod-sageit-cert.yaml
stack_tags:
  Department: "Platform"
  Project: "Infrastructure"
  OwnerEmail: "it@sagebase.org"
parameters:
  Listener80Arn: "arn:aws:elasticloadbalancing:us-east-1:237179673806:listener/app/awseb-AWSEB-GFSO0GTC8UY2/ecfe9b49dab884b5/a6ca336d1ff1bc50"
  Listener443Arn: "arn:aws:elasticloadbalancing:us-east-1:237179673806:listener/app/awseb-AWSEB-GFSO0GTC8UY2/ecfe9b49dab884b5/3731edc80a584ae2"
  HttpRedirectTarget: "synapse-login-scipoolprod.scipoolprod.org"
  FriendlyEndpoint: "sc.sageit.org"
