template_path: ssm-vars.j2
stack_name: synapse-login-scipoolprod-vars
stack_tags:
  Department: "Platform"
  Project: "Infrastructure"
  OwnerEmail: "it@sagebase.org"
sceptre_user_data:
  Prefix: service-catalog
  Variables:
    - SynapseOauthClientId='100053'
    - AwsRegion='us-east-1'
    - SessionTimeoutSeconds='28800'
    - SessionNameClaims='userid'
    - SessionTagClaims='sub,userid,team,user_name,company,given_name,family_name'
    - RedirectUris='https://synapse-login-scipoolprod.scipoolprod.org/synapse,https://connect.scipoolprod.org/oauth2/idpresponse'
    # Synapse team mapping
    # 3407239 scipool-admin
    #  273957 Sage Bionetworks
    # 3409010 scipoolprod-internal
    # 3412678 ampad-workinggroup
    # 3412679 ampad-portalusers
    # 3409011 scipoolprod-external
    - Name: TeamToRoleArnMap
      Value: '[
                {"teamId":"3407239","roleArn":"arn:aws:iam::237179673806:role/ServiceCatalogEndusers"},
                {"teamId":"273957","roleArn":"arn:aws:iam::237179673806:role/ServiceCatalogEndusers"},
                {"teamId":"3409010","roleArn":"arn:aws:iam::237179673806:role/ServiceCatalogEndusers"},
                {"teamId":"3412678","roleArn":"arn:aws:iam::237179673806:role/ServiceCatalogExternalEndusers"},
                {"teamId":"3412679","roleArn":"arn:aws:iam::237179673806:role/ServiceCatalogExternalEndusers"},
                {"teamId":"3409011","roleArn":"arn:aws:iam::237179673806:role/ServiceCatalogExternalEndusers"}
             ]'
