dist: bionic
language: python
python: 3.7
cache: pip
branches:
  only:
  - develop
  - prod
install:
  - pip install awscli pre-commit sceptre sceptre-ssm-resolver travis-wait-improved
stages:
  - name: validate
  - name: deploy-develop
    if: type = push AND branch = develop
  - name: deploy-prod   # deploy to all production AWS accounts
    if: type = push AND branch = prod
jobs:
  fast_finish: true
  include:
    - stage: validate
      script:
        - pre-commit run --all-files
    - stage: deploy-develop
      script:
        - ./setup_aws_profiles.sh || travis_terminate 1
        - travis-wait-improved --timeout 30m sceptre --var "profile=develop" launch --yes develop
    - stage: deploy-prod
      script:
        - ./setup_aws_profiles.sh || travis_terminate 1
        - travis-wait-improved --timeout 30m sceptre --var "profile=prod" launch --yes prod
    - stage: deploy-prod
      script:
        - ./setup_aws_profiles.sh || travis_terminate 1
        - travis-wait-improved --timeout 30m sceptre --var "profile=strides" launch --yes strides
