template_path: app.yaml
stack_name: synapse-login
stack_tags:
  Department: "Platform"
  Project: "Infrastructure"
  OwnerEmail: "it@sagebase.org"
depedencies:
  - scipoolprod/synapse-login-base.yaml
parameters:
  AppDeployBucketName: "org-sagebase-scipoolprod-synapse-login"
  SnsBounceNotificationEndpoint: "aws.scipoolprod@sagebase.org"
  SnsNotificationEndpoint: "aws.scipoolprod@sagebase.org"
  DNSHostname: "synapse-login"
  DNSDomain: "scipoolprod.org"
  EC2InstanceType: "t3.nano"
  VpcName: "internalpoolvpc"
  LoginSessionTimeout: "4320"
  SynapseOAuthClientId: "100050"
  SynapseOAuthClientSecret: !ssm /synapse-login/SynapseOAuthClientSecret
