template_path: app-extra.yaml
stack_name: synapse-login-strides-extra
dependencies:
  - strides/synapse-login-strides-sageit-cert.yaml
stack_tags:
  Department: "Platform"
  Project: "Infrastructure"
  OwnerEmail: "it@sagebase.org"
parameters:
  Listener80Arn: "arn:aws:elasticloadbalancing:us-east-1:423819316185:listener/app/awseb-AWSEB-WX1JT0B9V11G/e910ca24bdeffb8f/4faeb63ac98bd95b"
  Listener443Arn: "arn:aws:elasticloadbalancing:us-east-1:423819316185:listener/app/awseb-AWSEB-WX1JT0B9V11G/e910ca24bdeffb8f/e38f844ce3026ee7"
  HttpRedirectTarget: "synapse-login-strides.sagebio-strides.org"
  FriendlyEndpoint: "strides.sc.sageit.org"
  CertificateArn: !stack_output_external synapse-login-strides-sageit-cert::SSLCertificateSageIT
