project_code: "sage-bionetworks"
region: {{ var.region | default("us-east-1") }}
template_key_prefix: {{ environment_variable.TRAVIS_BRANCH | default("testing") }}
admincentral_cf_bucket: "bootstrap-awss3cloudformationbucket-19qromfd235z9"
