template_path: base.yaml
stack_name: synapse-login-scipooldev-base
stack_tags:
  Department: "Platform"
  Project: "Infrastructure"
  OwnerEmail: "it@sagebase.org"
parameters:
  DNSDomainName: "scipooldev.org"
  BeanstalkAppName: "synapse-login"
