template_path: app-extra.yaml
stack_name: synapse-login-scipooldev-extra
dependencies:
  - develop/synapse-login-scipooldev.yaml
stack_tags:
  Department: "Platform"
  Project: "Infrastructure"
  OwnerEmail: "it@sagebase.org"
parameters:
  Listener80Arn: "arn:aws:elasticloadbalancing:us-east-1:465877038949:listener/app/awseb-AWSEB-670099BKSPFO/fe2c5f1c9b5905cd/9435d431899b15e7"
  Listener443Arn: "arn:aws:elasticloadbalancing:us-east-1:465877038949:listener/app/awseb-AWSEB-670099BKSPFO/fe2c5f1c9b5905cd/24eaae2248925912"
  HttpRedirectTarget: "synapse-login-scipooldev.scipooldev.org"
  FriendlyEndpoint: "sc-dev.sageit.org"
  CertificateArn: !stack_output_external synapse-login-scipooldev-sageit-cert::SSLCertificateSageIT
