name: deploy

on:
  pull_request, push:
    branches: [ 'develop', 'prod' ]

concurrency:
  group: ${{ github.workflow }}

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - uses: pre-commit/action@v3.0.0
  deploy-develop:
    name: deploy-develop
    runs-on: ubuntu-latest
    if: {{ github.event_name == 'push' && github.ref_name == 'develop' }}
    needs: [ "pre-commit" ]
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Assume AWS Role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::465877038949:role/sagebase-github-oidc-scip-ProviderRolesynapselogin-N5UM6GWSWVWN
          role-session-name: GitHubActions-${{ github.repository_owner }}-${{ github.event.repository.name }}-${{ github.run_id }}
          role-duration-seconds: 900
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sceptre sceptre-ssm-resolver
      - name: 'Sceptre launch'
        uses: Sceptre/github-ci-action@master
        with:
          sceptre_version: '4.1.0'
          sceptre_plugins: >-
            sceptre-ssm-resolver==1.1.4
          sceptre_subcommand: 'launch -y develop'
  deploy-prod:
    name: deploy-prod
    runs-on: ubuntu-latest
    if: {{ github.event_name == 'push' && github.ref_name == 'prod' }}
    needs: [ "pre-commit" ]
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Assume AWS Role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::237179673806:role/sagebase-github-oidc-scip-ProviderRolesynapselogin-16RNR2FUO69IS
          role-session-name: GitHubActions-${{ github.repository_owner }}-${{ github.event.repository.name }}-${{ github.run_id }}
          role-duration-seconds: 900
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sceptre sceptre-ssm-resolver
      - name: 'Sceptre launch'
        uses: Sceptre/github-ci-action@master
        with:
          sceptre_version: '4.1.0'
          sceptre_plugins: >-
            sceptre-ssm-resolver==1.1.4
          sceptre_subcommand: 'launch -y prod'
  deploy-bmgfki:
    name: deploy-bmgfki
    runs-on: ubuntu-latest
    if: {{ github.event_name == 'push' && github.ref_name == 'prod' }}
    needs: [ "pre-commit" ]
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Assume AWS Role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::464102568320:role/sagebase-github-oidc-bmgf-ProviderRolesynapselogin-2M555XCM7SX4
          role-session-name: GitHubActions-${{ github.repository_owner }}-${{ github.event.repository.name }}-${{ github.run_id }}
          role-duration-seconds: 900
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sceptre sceptre-ssm-resolver
      - name: 'Sceptre launch'
        uses: Sceptre/github-ci-action@master
        with:
          sceptre_version: '4.1.0'
          sceptre_plugins: >-
            sceptre-ssm-resolver==1.1.4
          sceptre_subcommand: 'launch -y bmgfki'
  # Need STRIDES OIDC setup first
  # deploy-strides:
  #   name: deploy-strides
  #   runs-on: ubuntu-latest
  #   if: {{ github.event_name == 'push' && github.ref_name == 'prod'}}
  #   needs: [ "pre-commit" ]
  #   permissions:
  #     id-token: write
  #     contents: read
  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v3
  #   - name: Assume AWS Role
  #     uses: aws-actions/configure-aws-credentials@v1
  #     with:
  #       aws-region: us-east-1
  #       role-to-assume:
  #       role-session-name: GitHubActions-${{ github.repository_owner }}-${{ github.event.repository.name }}-${{ github.run_id }}
  #       role-duration-seconds: 900
  #   - name: Install dependencies
  #     run: |
  #       python -m pip install --upgrade pip
  #       pip install sceptre sceptre-ssm-resolver
  #   - name: 'Sceptre launch'
  #       uses: Sceptre/github-ci-action@master
  #       with:
  #         sceptre_version: '4.0.2'
  #         sceptre_plugins: >-
  #           sceptre-ssm-resolver==1.1.4
  #         sceptre_subcommand: 'launch -y strides'
